// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdGUeohZLkadSBzOJC_XEf75vKHudYBkk',
    appId: '1:271868732814:web:4ff26bd0ba54c40a6d70df',
    messagingSenderId: '271868732814',
    projectId: 'nove-store',
    authDomain: 'nove-store.firebaseapp.com',
    storageBucket: 'nove-store.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU-Ksvybd8klrDi2yF7-7dps9pcyvOLgM',
    appId: '1:271868732814:android:1d98bf06922f73d46d70df',
    messagingSenderId: '271868732814',
    projectId: 'nove-store',
    storageBucket: 'nove-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEOCCwZoZpxa3gwiXZrMmcyUYxLNMTvMA',
    appId: '1:271868732814:ios:80832d198ed8872c6d70df',
    messagingSenderId: '271868732814',
    projectId: 'nove-store',
    storageBucket: 'nove-store.firebasestorage.app',
    iosBundleId: 'com.example.novaStore',
  );
}
